// Code generated by cmd/openapi-gen; DO NOT EDIT.
package httpapi

import (
	"net/http"

	"github.com/gorilla/mux"
)

// ServerInterface represents handlers generated from api/openapi.yaml.
type ServerInterface interface {
	// (POST /v1/shorten)
	PostV1Shorten(w http.ResponseWriter, r *http.Request)
}

// RegisterHandlers registers generated OpenAPI handlers.
func RegisterHandlers(router *mux.Router, si ServerInterface) {
	router.HandleFunc("/v1/shorten", si.PostV1Shorten).Methods(http.MethodPost)
}
