package main

import (
	"fmt"
	"os"
	"path/filepath"
)

const generatedContract = `// Code generated by cmd/openapi-gen; DO NOT EDIT.
package httpapi

import (
	"net/http"

	"github.com/gorilla/mux"
)

// ServerInterface represents handlers generated from api/openapi.yaml.
type ServerInterface interface {
	// (POST /v1/shorten)
	PostV1Shorten(w http.ResponseWriter, r *http.Request)
}

// RegisterHandlers registers generated OpenAPI handlers.
func RegisterHandlers(router *mux.Router, si ServerInterface) {
	router.HandleFunc("/v1/shorten", si.PostV1Shorten).Methods(http.MethodPost)
}
`

func main() {
	sourceSpecPath := filepath.Clean("api/openapi.yaml")
	targetSpecPath := filepath.Clean("internal/httpapi/swagger/openapi.yaml")
	targetContractPath := filepath.Clean("internal/httpapi/openapi.gen.go")

	spec, err := os.ReadFile(sourceSpecPath)
	if err != nil {
		fail("read source OpenAPI spec", err)
	}

	if err := os.WriteFile(targetSpecPath, spec, 0o644); err != nil {
		fail("write embedded OpenAPI spec", err)
	}

	if err := os.WriteFile(targetContractPath, []byte(generatedContract), 0o644); err != nil {
		fail("write generated OpenAPI contract", err)
	}
}

func fail(action string, err error) {
	fmt.Fprintf(os.Stderr, "failed to %s: %v\n", action, err)
	os.Exit(1)
}
